# Generated by Django 3.0.6 on 2020-06-10 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description du cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Orb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orb', models.FloatField(default=6.0, verbose_name='orb')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=30, verbose_name='Planète')),
            ],
        ),
        migrations.CreateModel(
            name='SunVenusAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('true', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('active', models.BooleanField(default=False, verbose_name='enregistrement actif ?')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2', verbose_name='cycle')),
                ('orb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb')),
            ],
            options={
                'db_table': 'sun_venus_aspects',
            },
        ),
        migrations.CreateModel(
            name='SunVenusCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2')),
                ('orb', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb')),
            ],
            options={
                'db_table': 'sun_venus_coverages',
            },
        ),
        migrations.CreateModel(
            name='SunVenusConjunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Type de conjonction')),
                ('true', models.BooleanField(default=False, verbose_name='conjonction exacte ?')),
                ('active', models.BooleanField(default=False, verbose_name='enregistrement actif ?')),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspects.SunVenusAspect', verbose_name='aspect')),
            ],
            options={
                'db_table': 'sun_venus_conjunctions',
            },
        ),
        migrations.AddField(
            model_name='cycle2',
            name='planet1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aspects.Planet', verbose_name='planète 1'),
        ),
        migrations.AddField(
            model_name='cycle2',
            name='planet2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aspects.Planet', verbose_name='planète 2'),
        ),
    ]
