# Generated by Django 3.0.6 on 2020-06-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='planet',
            new_name='name',
        ),
    ]
