# Generated by Django 3.0.6 on 2020-06-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0003_auto_20200610_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orb',
            old_name='orb',
            new_name='value',
        ),
    ]
