# Generated by Django 3.0.6 on 2020-06-18 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0004_auto_20200611_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sunvenusaspect',
            options={'ordering': ['-angle', '-orb']},
        ),
        migrations.CreateModel(
            name='SaturnJupiterCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('cycle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2', verbose_name='cycle')),
                ('orb', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb')),
            ],
            options={
                'db_table': 'saturn_jupiter_coverages',
            },
        ),
        migrations.CreateModel(
            name='SaturnJupiterAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('true', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('active', models.BooleanField(default=False, verbose_name='enregistrement actif ?')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2', verbose_name='cycle')),
                ('orb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb')),
            ],
            options={
                'db_table': 'saturn_jupiter_aspects',
                'ordering': ['-angle', '-orb'],
            },
        ),
    ]
