# Generated by Django 3.0.6 on 2020-06-21 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0006_auto_20200620_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunMercuryAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('true', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('active', models.BooleanField(default=False, verbose_name='enregistrement actif ?')),
            ],
            options={
                'db_table': 'sun_mercury_aspects',
                'ordering': ['-angle', '-orb'],
            },
        ),
        migrations.AlterField(
            model_name='cycle2',
            name='description',
            field=models.TextField(blank=True, verbose_name='information complémentaire'),
        ),
        migrations.AlterField(
            model_name='cycle2',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='est un cycle interne ?'),
        ),
        migrations.AlterField(
            model_name='cycle2',
            name='planet2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aspects.Planet', verbose_name='planète 2'),
        ),
        migrations.AlterField(
            model_name='saturnjupiteraspect',
            name='active',
            field=models.BooleanField(default=False, verbose_name='enregistrement actif ?'),
        ),
        migrations.AlterField(
            model_name='sunvenusaspect',
            name='active',
            field=models.BooleanField(default=False, verbose_name='enregistrement actif ?'),
        ),
        migrations.AlterField(
            model_name='sunvenusconjunction',
            name='active',
            field=models.BooleanField(default=False, verbose_name='enregistrement actif ?'),
        ),
        migrations.CreateModel(
            name='SunMercuryCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('angle', models.FloatField(default=0.0, verbose_name='angle')),
                ('cycle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2', verbose_name='cycle')),
                ('orb', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb')),
            ],
            options={
                'db_table': 'sun_mercury_coverages',
            },
        ),
        migrations.CreateModel(
            name='SunMercuryConjunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='Type')),
                ('true', models.BooleanField(default=False, verbose_name='Est-elle exacte ?')),
                ('active', models.BooleanField(default=False, verbose_name='enregistrement actif ?')),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspects.SunMercuryAspect', verbose_name='aspect')),
            ],
            options={
                'db_table': 'sun_mercury_conjunctions',
            },
        ),
        migrations.AddField(
            model_name='sunmercuryaspect',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Cycle2', verbose_name='cycle'),
        ),
        migrations.AddField(
            model_name='sunmercuryaspect',
            name='orb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspects.Orb', verbose_name='orb'),
        ),
    ]
