# Generated by Django 3.0.6 on 2020-05-28 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Houses system, as human readable name')),
                ('code', models.CharField(default='', max_length=1, verbose_name='Houses system code')),
                ('default', models.BooleanField(default=False, verbose_name='Système par défaut ?')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(default='Paris', max_length=150, verbose_name='Ville')),
                ('latitude', models.FloatField(default=48.8534, verbose_name='latitude')),
                ('longitude', models.FloatField(default=2.3488, verbose_name='longitude')),
                ('altitude', models.FloatField(default=25.0, verbose_name='altitude')),
                ('time_zone', models.CharField(blank=True, default='Europe/Paris', max_length=80, verbose_name='fuseau horaire')),
                ('context', models.CharField(blank=True, default='75, Paris, Île-de-France', max_length=120, verbose_name='contexte')),
            ],
        ),
        migrations.CreateModel(
            name='SiderealMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sidereal mode, as human readable name')),
                ('code', models.CharField(default='', max_length=150, verbose_name='Sidereal code fof the mode')),
                ('default', models.BooleanField(default=False, verbose_name='Is default name ?')),
            ],
        ),
        migrations.CreateModel(
            name='TropicalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='afficher ?')),
                ('default', models.BooleanField(default=False, verbose_name='est la configuration par défaut ?')),
                ('houses_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.HousesSystem', verbose_name='système de maisons')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('further_information', models.CharField(blank=True, max_length=80, verbose_name='information complémentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Location', verbose_name='localisation')),
            ],
        ),
        migrations.CreateModel(
            name='SiderealConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='afficher ?')),
                ('default', models.BooleanField(default=False, verbose_name='est la configuration par défaut ?')),
                ('houses_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.HousesSystem', verbose_name='système de maisons')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.SiderealMode', verbose_name='mode')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='afficher ?')),
                ('default', models.BooleanField(default=False, verbose_name='est la configuration par défaut ?')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidereal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.SiderealConfiguration', verbose_name='configuration sidérale')),
                ('tropical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.TropicalConfiguration', verbose_name='configuration tropicale')),
            ],
        ),
    ]
