# Generated by Django 3.0.6 on 2020-05-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='configuration_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='theme.Configuration'),
            preserve_default=False,
        ),
    ]
