# Generated by Django 3.0.6 on 2020-05-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20200528_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='sidereal',
            new_name='configuration_sidereal',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='tropical',
            new_name='configuration_tropical',
        ),
    ]
